"""Safe project translation and gem5 process execution."""

from workbench.execution.controller import (
    AsyncExecutionController,
    ExecutionControllerError,
    default_build_jobs,
)
from workbench.execution.installation import (
    BINARY_ENVIRONMENT_VARIABLE,
    ROOT_ENVIRONMENT_VARIABLE,
    Gem5DiscoveryError,
    Gem5ProbeError,
    discover_gem5_installation,
    installation_fingerprint,
    probe_gem5_installation,
)
from workbench.execution.models import (
    BOARD_CACHE_PORT,
    BOARD_MEMORY_PORT,
    BOARD_PROCESSOR_PORT,
    BOARD_WORKLOAD_PORT,
    DDR3_MEMORY_TYPE_ID,
    NO_CACHE_TYPE_ID,
    SE_WORKLOAD_TYPE_ID,
    SIMPLE_BOARD_TYPE_ID,
    SIMPLE_PROCESSOR_TYPE_ID,
    SUPPORTED_COMPONENT_TYPE_IDS,
    BuildRequest,
    ExecutionPlan,
    Gem5Installation,
    Gem5Probe,
    JobKind,
    JobSnapshot,
    JobState,
    RunHandle,
    RunRequest,
    WorkloadKind,
)
from workbench.execution.translation import (
    TranslationError,
    dumps_execution_plan,
    translate_project,
)

__all__ = [
    "AsyncExecutionController",
    "BINARY_ENVIRONMENT_VARIABLE",
    "BOARD_CACHE_PORT",
    "BOARD_MEMORY_PORT",
    "BOARD_PROCESSOR_PORT",
    "BOARD_WORKLOAD_PORT",
    "BuildRequest",
    "DDR3_MEMORY_TYPE_ID",
    "ExecutionControllerError",
    "ExecutionPlan",
    "Gem5DiscoveryError",
    "Gem5Installation",
    "Gem5Probe",
    "Gem5ProbeError",
    "JobKind",
    "JobSnapshot",
    "JobState",
    "NO_CACHE_TYPE_ID",
    "ROOT_ENVIRONMENT_VARIABLE",
    "RunHandle",
    "RunRequest",
    "SE_WORKLOAD_TYPE_ID",
    "SIMPLE_BOARD_TYPE_ID",
    "SIMPLE_PROCESSOR_TYPE_ID",
    "SUPPORTED_COMPONENT_TYPE_IDS",
    "TranslationError",
    "WorkloadKind",
    "default_build_jobs",
    "discover_gem5_installation",
    "dumps_execution_plan",
    "installation_fingerprint",
    "probe_gem5_installation",
    "translate_project",
]
